import {StyleSheet} from 'react-native';
import {black, black2, blue2, gray, gray1, red} from '../../constants/colors';
import FontFamilies from '../../constants/Fonts';
import sizeHelper from '../../helpers/sizeHelper';
const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  headerContainer: {
    backgroundColor: black2,
  },
  containerStyle: {
    marginTop: sizeHelper.calHp(40),
    width: '92%',
    margin: sizeHelper.calHp(50),
    padding: sizeHelper.calHp(30),
    borderRadius: sizeHelper.calHp(20),
    alignSelf: 'center',
    backgroundColor: '#FFFFFF',
  },
  rowComponents: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: sizeHelper.calHp(26),
    width: '100%',
  },
  textContainer: {},
  headingTxt: {
    color: '#000000',
    fontSize: sizeHelper.calHp(40),
    fontFamily: 'InterMedium',
  },
  subHeading: {
    color: '#B5B9C0',
    fontSize: sizeHelper.calHp(30),
    fontFamily: 'InterMedium',
  },
  graphContainer: {
    height: sizeHelper.calHp(500),
    width: '100%',
    alignSelf: 'center',
    justifyContent: 'center',
  },
  TableHeaderContainer: {
    width: '100%',
    flexDirection: 'row',
    backgroundColor: '#e9e9e9',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: sizeHelper.calWp(30),
    padding: sizeHelper.calHp(20),
  },
  fileIcon: {
    width: sizeHelper.calHp(80),
    backgroundColor: '#F8F8F9',
    height: sizeHelper.calHp(80),
    borderColor: '#E3E6E9',
    borderWidth: 1,
    backgroundColor: '#F8F8F9',
    borderRadius: sizeHelper.calHp(10),
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    right: 0,
  },
  vendorNameText: {
    flex: 1,
    fontFamily: FontFamilies.InterSemiBold,
    fontWeight: '500',
    color: black,
    fontSize: sizeHelper.calHp(30),
  },
  TableHeaderAmount: {
    flex: 1,
    fontFamily: FontFamilies.InterSemiBold,
    fontWeight: '500',
    color: '#000000',
    fontSize: sizeHelper.calHp(30),
    textAlign: 'left',
  },
  rowContainer: {
    flexDirection: 'row',
    width: '100%',
    paddingHorizontal: sizeHelper.calWp(30),
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: sizeHelper.calHp(10),
  },
  nameText: {
    fontFamily: 'InterMedium',
    color: black,
    textAlign: 'left',
    fontSize: sizeHelper.calHp(30),
  },
  amountText: {
    fontFamily: 'InterMedium',
    color: black,
    // paddingTop: sizeHelper.calHp(10),
    textAlign: '',
    fontSize: sizeHelper.calHp(30),
  },
  itemsContainer: {
    justifyContent: 'space-between',
    width: '100%',
  },
  row: {
    marginTop: sizeHelper.calHp(40),
    flexDirection: 'row',
    width: '92%',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: sizeHelper.calWp(30),
    paddingVertical: sizeHelper.calHp(30),
    backgroundColor: 'white',
    alignSelf: 'center',
    borderRadius: sizeHelper.calHp(20),
    // borderWidth: 1,
    borderColor: '#8A929F',
  },

  textContainerWrap: {
    flexDirection: 'row',
    borderWidth: 1,
    paddingHorizontal: sizeHelper.calWp(10),
    paddingVertical: sizeHelper.calHp(5),
    borderRadius: sizeHelper.calHp(10),
    borderColor: '#8A929F',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  text: {
    fontSize: sizeHelper.calHp(30),
    fontWeight: '400',
    color: 'black',
    fontFamily: 'InterMedium',
    paddingHorizontal: sizeHelper.calWp(20),
    paddingVertical: sizeHelper.calHp(10),
  },
  modalContainerr: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0,0.5)',
  },
  modalContentt: {
    backgroundColor: 'white',
    width: '100%',
    padding: sizeHelper.calHp(40),
    borderTopLeftRadius: sizeHelper.calHp(30),
    borderTopRightRadius: sizeHelper.calHp(30),
    height: '70%',
  },
  modalText: {
    fontSize: sizeHelper.calHp(40),
    fontWeight: '600',
    color: 'black',
    fontFamily: 'InterBold',
  },
  closeButton: {
    position: 'absolute',
    right: 10,
    padding: 10,
  },
  headerRowModal: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: sizeHelper.calWp(20),
    paddingVertical: sizeHelper.calWp(20),
    borderBottomWidth: 1,
    borderColor: gray1,
  },
  itemText: {
    paddingHorizontal: sizeHelper.calWp(30),
    paddingVertical: sizeHelper.calWp(20),
    fontSize: sizeHelper.calHp(28),
    fontWeight: '500',
    color: 'black',
    fontFamily: 'InterMedium',
  },
});

export default styles;
